###################################################"
# fichier de config pour le profil: TEST
###################################################"
###################################################"

debug: false

spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                globally_quoted_identifiers: true        
        show-sql: true
        
elasticsearch:
    cluster-name:
    cluster-nodes:
    properties:
        path:
          logs: target/elasticsearch/log
          data: target/elasticsearch/data
        http:
          enabled: true

            