###################################################"
# fichier de config pour le profil: TEST
###################################################"
###################################################"

debug: false

spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                globally_quoted_identifiers: true        
        show-sql: true


            