/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template angular-lab:springboot/src/main/java/security/RestAuthenticationSuccessHandler.p.vm.java
 */
package com.jaxio.demo.security;

import java.io.IOException;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.core.Authentication;
import org.springframework.security.web.authentication.SimpleUrlAuthenticationSuccessHandler;
import org.springframework.stereotype.Component;

import com.jaxio.demo.domain.AppUser;
import com.jaxio.demo.repository.AppUserRepository;

/**
 * Spring Security success handler, specialized for Ajax requests.
 */
@Component
public class RestAuthenticationSuccessHandler extends SimpleUrlAuthenticationSuccessHandler {

    private final Logger log = LoggerFactory.getLogger(this.getClass());

    @Inject
    private AppUserRepository appUserRepository;

    @Override
    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws ServletException,
            IOException {

        log.info("inside RestAuthenticationSuccessHandler.onAuthenticationSuccess");

        // try to find a corresponding user with a login
        AppUser appUser = appUserRepository.findByLogin(authentication.getName());

        // send this user back to the browser 
        SecurityUtils.sendResponse(response, HttpServletResponse.SC_OK, appUser);
    }
}
