/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template angular-lab:springboot/src/test/java/utils/JsonUtilsTest.p.vm.java
 */
package com.jaxio.demo.utils;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.io.Serializable;

import org.junit.Test;

public final class JsonUtilsTest {

    @Test
    public void testConvertObjectToJsonBytes() {

        TestObject object = new TestObject();
        object.setId("1");
        object.setTitle("test");

        try {
            String result = new String(JsonUtils.convertObjectToJsonBytes(object));

            assertEquals(result, "{\"title\":\"test\",\"id\":\"1\"}");
        } catch (IOException e) {
            e.printStackTrace();
            fail();
        }
    }

}

class TestObject implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3155799279999651919L;

    private String title;

    private String id;

    public TestObject() {
        super();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}